### ISSUE TITLE
CI build fails

### ISSUE THREAD

**Issue by brenzi** [integritee-network/crowdloan#31]
@Alirazadar I assume, your last changes were on the develop branch (I suggest to use more descriptive branch names in the future. "beautify" and "develop" don't tell me much. also, it would be good to know which one is deployed the TRH-test server), so I merged that one into master. However, as you can see in CI, master doesn't build. Can you have a look please?

**Comment by brenzi** [comment]
github actions complains:
```

Run yarn install
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 8s 166ms
➤ YN0000: Failed with errors in 8s 174ms
(node:1717) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
➤ YN0032: node-addon-api@npm:3.2.1: Implicit dependencies on node-gyp are discouraged
➤ YN0032: bufferutil@npm:4.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0032: utf-8-validate@npm:5.0.5: Implicit dependencies on node-gyp are discouraged
Error: Process completed with exit code 1.
```

**Comment by brenzi** [comment]
If I build it myself, I see a bit more:
```
➤ YN0001: │ Error: bip32-ed25519@git+ssh://git@github.com/Zondax/bip32-ed25519.git#commit=0949df01b5c93885339bc28116690292088f6134: Repository clone failed: Child "git" exited with exit code 128

Cloning into '/tmp/xfs-b5e1a3ee'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (/mnt/d/integritee/crowdloan/.yarn/releases/yarn-berry.cjs:2:404557)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
➤ YN0000: └ Completed in 3m 49s
➤ YN0000: Failed with errors in 3m 49s
```
will try a quick fix to replace git+ssh with git+https in lock file

**Comment by brenzi** [comment]
fix didn't work. may be related to 
https://github.com/substrate-developer-hub/substrate-front-end-template/issues/176

**Comment by brenzi** [comment]
upstream has upgraded deps, will try that

**Comment by brenzi** [comment]
fixed he wrong lock file when trying before. trying with yarn.lock now ;-)

**Comment by brenzi** [comment]
this one seems fixed. next one came up....
